apiVersion: apps/v1
kind: Deployment
metadata:
  name: pictrs
spec:
  selector:
    matchLabels:
      app: lemmy
      service: pictrs
  replicas: 1
  template:
    metadata:
      labels:
        app: lemmy
        service: pictrs
    spec:
      containers:
        - name: pictrs
          image: asonix/pictrs:0.3.1
          imagePullPolicy: Always
          env:
            - name: PICTRS__API_KEY
              valueFrom:
                secretKeyRef:
                  name: pictrs
                  key: API_KEY
            - name: RUST_LOG
              value: "warn"
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: pictrs
              mountPath: /mnt
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
              ephemeral-storage: 500Mi
            limits:
              memory: 1Gi
              ephemeral-storage: 1Gi
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      volumes:
        - name: pictrs
          persistentVolumeClaim:
            claimName: pictrs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lemmy
    service: pictrs
  name: pictrs
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: lemmy
    service: pictrs
  type: ClusterIP
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: pictrs #this name will also be used for naming the generated kubernetes secret
spec:
  itemPath: "vaults/eum332ncoupzqyxp2po3kwhjqe/items/lemmy_pictrs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pictrs
spec:
  storageClassName: nfs-freenas
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi