apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchy-postgres-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/CrunchyData/postgres-operator-examples.git
    targetRevision: f94c261ef1c83bca9aa3e5d9894710ab3e03cd7e
    path: 'kustomize/install/default'
