apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: h5b-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/JustinLex/jlh-h5b.git
      revision: HEAD
      directories:
      - path: applications/*
