---
- hosts: cloyster.home.jlh.name
  become: yes
  vars_files: ["vars.yml"]
  tasks:

    # Update system
    - name: Update system
      ansible.builtin.apt:
        upgrade: safe
        update_cache: yes

    # Setup SELinux https://wiki.debian.org/SELinux/Setup

    # k3s selinux bits
    #    ${package_installer} install -y container-selinux
    #    ${package_installer} install -y https://${rpm_site}/k3s/${rpm_channel}/common/${rpm_site_infix}/noarch/k3s-selinux-0.4-1.${rpm_target}.noarch.rpm

    # Mount NFS
    - name: mount NFS share
      ansible.posix.mount:
        fstype: nfs
        src: freenas.home.jlh.name:/mnt/solid/kubernetes
        path: /mnt
        opts: noauto,x-systemd.automount,x-systemd.mount-timeout=60,_netdev
        state: mounted

    # Install CRI-O https://cri-o.io/
    - name: Install CRI-O repository keys
      ansible.builtin.apt_key:
        url: "{{ item }}"
        state: present
      loop:
        - "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ k8s_version }}/Debian_11/Release.key"
        - "https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/Debian_11/Release.key"

    - name: Install CRI-O repositories
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/"
        - "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/cri-o:/{{ k8s_version }}/Debian_11/"

    - name: Install CRI-O
      ansible.builtin.apt:
        name:
          - cri-o
          - cri-o-runc
        update_cache: yes
        state: latest

    # Install k3s https://github.com/k3s-io/k3s-ansible
    - name: Download k3s binary
      ansible.builtin.get_url:
        url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s
        checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt
        dest: /usr/local/bin/k3s
        owner: root
        group: root
        mode: 0755

    - name: Install k3s service
      ansible.builtin.copy:
        src: "k3s.service"
        dest: "/etc/systemd/system/k3s.service"
        owner: root
        group: root
        mode: 0644

    - name: Enable and restart K3s service
      ansible.builtin.systemd:
        name: k3s
        daemon_reload: yes
        state: restarted
        enabled: yes
