apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-helm
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: nextcloud
    repoURL: https://nextcloud.github.io/helm/
    targetRevision: "3.1.*"
    helm:
      releaseName: nextcloud
      # Having values inline here is a bit of a hack until values files are supported
      # https://github.com/argoproj/argo-cd/issues/2789
      values: |
        replicaCount: 3
        image:
          tag: 24-fpm
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 100g
            nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
            nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          tls:
            - hosts:
              - cloud.jlh.name
              secretName: cloud-jlh-name-tls
        nextcloud:
          host: cloud.jlh.name
          existingSecret:
            enabled: true
            secretName: nextcloud-secrets
            usernameKey: admin-username
            passwordKey: admin-password
          extraEnv:
          - name: PHP_MEMORY_LIMIT
            value: "2G"
          - name: PHP_UPLOAD_LIMIT
            value: "100G"
        nginx:
          enabled: true
        internalDatabase:
          enabled: false
        externalDatabase:
          enabled: true
          type: postgresql
          host: "nextcloud-db:5432"
          database: nextcloud
          existingSecret:
            enabled: true
            secretName: kubegres-passwords
            usernameKey: username
            passwordKey: appPassword
        redis:
          enabled: true
        cronjob:
          enabled: true
        persistence:
          enabled: true
          size: 2Ti
          accessMode: ReadWriteMany
          nextcloudData:
            enabled: true
        livenessProbe:
          initialDelaySeconds: 300
          timeOutSeconds: 10
