apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: basic-auth
spec:
  encryptedData:
    auth: AgAQ0vYkC+9utixMXiBflsoxHl9SRV57NVCpwH9E607sW9Lo9A+H8SsP0hEYCy8Dmis3FSCa1PnWzY83nBnMo88wsmrbUQg4AMfvu3zvrFMWCSiMdaodJfFDz6fSt2fbsDEXFYH/SpSRZXmtu2c5DpfSNVcU6w+xwcf0qoT3c3K2XgMeoO1ZXGU1vKYulubdj3Ab8qAP8SaHHmcyh1HSt8fi73UPrOcNuHQzrKynYUc6KPve99CRPuLzd7ysSuvBh/RBjYCOJZ/c+q8v5eXTVsilqT9e9acbbnGqnSiwSHSp7lHh126D4HxI5v6tY/WPqoK+oEy3tWCIr7b0xTjd0SRd0nYxMDJt3EL/ofT1SORhdY8bsMQ84RFaaOaZ+5q6NG6A8nYhBBoKAfc/DKlqufO5DtbJ+AFk2EXNxxffbXIjDBW7zbXjJFtDkih1UpRe4uQNRi3IMOovj41OkURuTTUPSpaaQHcIQ5jxS3Noso9/RPsfdYMsID9euov3OQiswl+L2NwiJxfzses6ylyFPMQb+ZuRdCiw7gXwB8ft/7SdptuWWVxPhBtldrlAz2IMlSS9EwDSWj93A4Owc1Y5CLM2W/EdGrpXSdKbaFHSrke0KD4R0i0wnHHvMIeP00kXgUYtXwX61NBNwMKBfdTX5q8nlZlKVeSBFjmfv8aQpTECuzzrFcPm/pV49Fk3xWdIYll5RPN5Q276k/y68Jkfr0zNhhG7wUMwr8QgzNAiM5SNRec8MOJ06vDa4bAeOYW49w==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: basic-auth

