apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  labels:
    app: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
        - name: factorio
          image: factoriotools/factorio:stable
          env:
            - name: LOAD_LATEST_SAVE # BOOL
              value: "true"
            - name: UPDATE_MODS_ON_START
              value: "true"
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: factorio-config
                  # Specify the key associated with the value
                  key: username
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: factorio-config
                  # Specify the key associated with the value
                  key: token
          resources:
            requests:
              cpu: 2
              memory: 5Gi
            limits:
              cpu: 6
              memory: 10Gi
          ports:
            - name: steam-discovery
              containerPort: 27015
              protocol: TCP
            - name: factorio
              containerPort: 34197
              protocol: UDP
          volumeMounts:
            - mountPath: "/factorio"
              name: factorio
        volumes:
          - name: factorio
            persistentVolumeClaim:
              claimName: viktor
