apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: viktor
spec:
  storageClassName: nfs-freenas
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
