apiVersion: v1
kind: Service
metadata:
  name: factorio-udp
spec:
  selector:
    app: factorio
  ports:
    - name: factorio
      port: 34197
      protocol: UDP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: factorio-tcp
spec:
  selector:
    app: factorio
  ports:
    - name: steam-discovery
      port: 27015
      protocol: TCP
  type: LoadBalancer