apiVersion: v1
kind: Service
metadata:
  name: factorio
spec:
  selector:
    app: factorio
  ports:
    - name: factorio
      port: 34197
      protocol: UDP
    - name: steam-discovery
      port: 27015
      protocol: TCP
  type: LoadBalancer