apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBsHUXSHTkqArVe21cHIYGs09kN7VZJjX+DXMmXxz6tXT00aXg/Ku5vil5rT90J7FN2rq6qTQ4RnZVMvgENjgKfHqW3WN4ReWr7ui6Fo45ME7Z4RWwAQMLJ9OIOwMZtBINU4zGhujL83dfJ3hOA7vsOKUOaihS0g29yLCNvClIdOrj5bHXjs6KaVcBu78yIdoSRDkzVzftkKOUXOoD+d+zkw7/QoUhjUpd218nyFZfdjfZS83tU/M1RKtlI7SnKEA6LVMy2hmAEO6Z2MnR8X6HYbcwayCcqmaGivEQFx7nJYQViQHPdvh5x0oYsQ27Jaxjdixq0CcfQJqF7hKj25AwuQs1+G9lEdXPAmgB/1uWhjcEgrfWOKIX+mqKvneuHVpj+Cs/V58G7xyNMZZaGfyOzCtdSr3hHllp3pH/Spk9ONuBydV4Kwx+0PH3ayX7+Zw0vOLT+Sn5R/73yIHR0yBYDmIYntB76L4idEvbpVm4ZF2sc9wS8rO59bnSKx+YHgEmeNydWpnQp6nalsA9jA+m4XUzYP45mwIwLH7bI7u++pxH9Nvc/cVM9Dcx2dK1lyJW7zQMal6jwdLs3drzTNlxhEw9W+7T4PxFN9NvxtqNcRFw+2fQA5FVU02e8gkWVFchEwBPkDusolQEWNQzLJnII0tJ46UScfsslsb/AoaHq+YbOWtBUAFPRb/sovasmI0TePj0MIq3HnAyF68LSlz9YBpiIUCJsEkTLhgsSK/qBT6bJ2vIBxijD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
