apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.1.*
    helm:
      releaseName: ingress-nginx
      parameters:
        # Use new chroot hardened controller
        - name: "controller.image.chroot"
          value: true
        # Become default IngressClass
        - name: "controller.watchIngressWithoutClass"
          value: true
        - name: "controller.ingressClassResource.name"
          value: "nginx"
        - name: "controller.ingressClassResource.enabled"
          value: true
        - name: "controller.ingressClassResource.default"
          value: true
        - name: "controller.ingressClassResource.controllerValue"
          value: "k8s.io/ingress-nginx"
        # Don't hide source IP
        - name: "controller.service.externalTrafficPolicy"
          value: "local"
