apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: geokey-secret
spec:
  encryptedData:
    OTR_GEOKEY: AgCN2/zdv3L861onB4JyT8B2jor5O8pf3AM5VsAHFweu+q1aC0yfbhpCMgTuteMdaIRFeW1TIKDgS+p+OwCVlyyTKj7vl5JiAsZ73wVmNwbPfIXmCCSvcKFFAWW7EzEbMuDYmPVEv4nmrDebC8lAsI+DK7P5tH5nSkGZ3sgh0He3gQdP/Nx9JkjioydFx1WCewDwyZyfQFp28Lb9ZVGbtXcVNdyphwHpwFyAjMp6Vp6qpmaOiuWMLbZIQy+tyc77X8h6vC9MLm1bz1f/VwCAuczEGhwV54eQkJE0ajXIbnxMIuWoeHms9S8C2elnVtVz1+W2NneKIgSbF4txc7inTvlxR0Fw07mPifDc6GLrdfF07ngArLTdX1V4HjnVviH03NC/T0RRfdwdvCxKllNseZY1VVZF/Qb7NYNsmEUVq2KBYARy/lewJc59DMy+zC3lslqbjBNXGmnPUKjMkEnazbkzQn1E8VjDltoq+AA0DbFZq6lTx209A9kic1Edk0tkYNG0TeFqk/ubI9eEIQRg0wZDjO+FaH6RvuaBUscEJ6EfntpE3O1cOzbHmlte6IIiAa++Kgdz/1nxQRZVjjKMi5aKREqrQ/QFf6UPZBH+hRoPkqYbks/LIU4se4gvFoGvi/V0Oo0lcBAYfUPwQxQX7S9N2z4IAhGRT2jqucxGEocz1USUxG9U0TSuTKCDANVu1yIOvZYPWZKOyix4iJO20zAJFqOXAbL0iCQHE8eFToOec5KmIbYIIk7Wug==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: geokey-secret

