apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: basic-auth
spec:
  encryptedData:
    auth: AgBz26CBWoUIC2XwuKpTFJBusKJkR6w+TiZZh7g1KokCMcdbfG8mrci5MyxKalzvZmXrYnh7bOk7kAB+p+AYiPWQlLQVy0FKznCqwg0orQ3I/ePXdLAcEuxivOfYzTjCd6Wa8TXbIjZ//UWfqjbiD4NgbWZB0DLxK8a+1EkZc4lorCjtTthh5tiaUKWbmgn/9oJC9dA2+1K6YOs9f72jUjX7pSgoHOgJfMl/QzyJGpst/qKUgnZW6wpUm0htp0EcLk21SrsH00nBlO8syLAjxf88v5lH+OlrgzWaSwUyCued9BjBf+fD0fDYQq6t8/fFsSFusP1D3i0jWaJA1/DiJ1YawNKdK4CW53sIYhxSJdn0aXeEC/BgWvUtFPcgV7ZiOyWRBDqwXiOwVRuqT7aauB4580Zjj+vyrZsZaUWvXhQzJg+xdJRxiyAHdsk2ar5nMAM+Ag7zRTzqWo5KTS5jZNimxNG2W/y5FJFg+gFgM8NX6FRXsogv3Wz9x/JFkswNid+DVo2So6mw5xKmiSvFnk5x0S+FOIzSCggtOYgNrSwA84ai0tcgcIQcH2A88w7ZTI6Gp5hJQdlBuFFjVLTqW3rkVKj8Xn/rHdm9XuD9caXiMKZEyGIsceVB6hsoA28Yx6iXTIzrb7xU/QJFh1i5IgXIwSOxuFWs9e81JUK0cvfHZf9iWDuXQDvlqYyQtQj50vVSbr3cWSMge8oGqlXI2I1S1/++jHl32pRtzbnCOVJ/ATaax4qk01QwtsdoPe4=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: basic-auth

