apiVersion: v1
kind: Service
metadata:
  name: owntracks
  labels:
    app: owntracks
spec:
  ports:
  - port: 80
    name: web
    targetPort: 8083
  clusterIP: None
  selector:
    app: owntracks
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: owntracks
spec:
  selector:
    matchLabels:
      app: owntracks # has to match .spec.template.metadata.labels
  serviceName: "owntracks"
  replicas: 1
  template:
    metadata:
      labels:
        app: owntracks # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: owntracks
        image: owntracks/recorder:latest
        args: ["--http-port", "8083"]
        env:
        - name: OTR_HTTPHOST
          value: "0.0.0.0"
        - name: OTR_LMDBSIZE
          value: "1048576000000" # 100 MiB, not sure if this is stored in memory or a PV
        - name: OTR_PRECISION
          value: "7"  # Street addresses for geotags are fetched with 150m^2 precision
        - name: OTR_GEOKEY  # API key for reverse geo
          valueFrom:
            secretKeyRef:
              name: geokey-secret
              key: OTR_GEOKEY
        ports:
        - containerPort: 8083
          name: web
        volumeMounts:
        - name: store
          mountPath: /store
      volumes:
        - name: store
          persistentVolumeClaim:
            claimName: store
      dnsConfig:  # Fix DNS resolution in Alpine 3.11 https://github.com/kubernetes/kubernetes/issues/64924 https://github.com/gliderlabs/docker-alpine/issues/539
        options:
          - name: ndots
            value: "1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: store
spec:
  storageClassName: nfs-freenas
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 16Gi
