apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: owntracks-config-secret
spec:
  encryptedData:
    recorder.conf: AgBXFLm0DlJs09/O3lI/NObX+fRzrAdPd9W+EOMmU390+3GH4wiwglfTEaywyMr45Lx2KqxAlqwPjpnzIRrnocVDS0958DUC6DLs1g4Aehyxe1BOpXAXurwhFatHGeR5tX/4eYN5hza/bPdUxYQJ5nEFSuLCnfaxcyQaSpfcnkLHbcTYiKOS9dBMdYnAUgde6353U6fot0Ps6oqSwd5sl3xZvpgBQT3DBgF+PIJhFqH+xbAf9CA8M0oQwt18wH8hpX7mMiL2yS3yr3/+dgtmYH41Iy6Ed5RsA0KSVNlEKpSq/ROqCGAzwQAUPpszDDbvZVSOJFfzai24vaN35E08ZMCEfdjCALbqoBiDqxIYjj6XN5pF9ESwqvCJP0q8jZHO7kFQdtVffDhFJC9BATweE5FDlVABBD/IL8VT79MN8tCl/QVY/mGlC4w63YYVKcYl4aSaDNkXZGerYRX1y3XaPsF/P4FdP+AvVvU7DZxeA039eZvYYAVTcdI/i52a54f1k9PL7C7U4wC59rvVuNQrk/k2nJsU96sCjakECMQNatkMnrTgxa5GkKeyMR+LUGqlwO+W4rRmFnR8atviZ/0Iwj/jQqLYrXYrHptW37e7gNDwGtw1Uq7LrvrsMgFyTRa3ISJiv1dvNCQ1kGq0gYygCHwOS4kQ5P6W/XWyyOvw+1au9I9UqFH2+njbGTVO42IiPvvDhsBWMp501pN/Uq8AGI9vaUnkZPzmDF2TundbIHXSvHT1hZdGEhGigwCOcQEZoplrzn1gaaDkqSYEXZw3ZJxi6kvBYvGn4EVnG1Y//t7xl9sZXq/bySBV7oyu+iepL3j+5LdcKndLL/CRkU4hkpebaUCnNTCDkHfp3ijAdgKlnts0j/KGF8piKDv/yWa87kiLqvJGM/PKdgy5WUXP
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: owntracks-config-secret

