apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: owntracks-config-secret
spec:
  encryptedData:
    recorder.conf: AgAsbDrHPQXdIdpduEyyhetzF2QWU1p/qXb6MOnUzDox4VFW2hnW/zy2I/1/lCen3EC0paSI7x2o1dWcxVE9YRV1ZxcR0oLFSpUbO80jLgOdFORwepSy1j5WDGMuPMuN+C5KQf6fwHFKIpxyYhwTtf4jx6BBg6IS+MpIpKjPLaeJXRU8UvWodbRsHeHjmIyzAHq4XxR+IK3o5mJpa3ht8n9NTJ0k4n8kCpsT2mPGh0Ipn2Gn22Q8iu8BHmxODskOaO7g63klzJhKmx5j8Ottu8BKWTcty1VFaQTiyuiRJiSIM1gNQM1y4HWffxct3MP1ZhPJbNRvJJmWhA10tq7q7BntHm2HZQCgCt3c8nv7apM7xThIiSeHxHsljz5vg+fytiF8Otz+/J3KT4zX0WMX3NG3bJynUGCSXTJ/VRJcFWcmwcrnVP/cFEqT/O0+eWvwpTXQB09NT6FK/7YZWZPtzBVqX2mteMW6oEq6j21I/okhMi432pAJKaBxwCGMBF14K0dH53y9AR5UzZvqL9pATubAlyZyYmFxDhAvhedI0Aw3Lej6lY4FgL2rmI0f5DDQ/yRTHL5IF3McM+Joo1bd1L6imBSddF5WzCk5SClLHK5W+kQODC58/7NV5sFpw5pnxBw0qWVn+FrfQH6KnaugK/RseCsSXN0vye61vfYqtDYIyYwBkIXbDGvbC26JMcwCheYN+vliAx3mmSOBSgP+6A7dbAYoxVkURgnF0jNQjQKVM+VKmNpWdfuQAXyCIMR8N+3ozWN5oVrdOp4L+2tcr4BL4M4HZkz36RrHusig3BNMH+3kAVHojCRUEbgi1lyvbZSGPUfAaMg7cSQJ29FaE6lSR2mO6feelKPk4Oo3eRFEnuDCtEzYOjIRm5fQOuZsKKJeBrCEv1ackHDrpKMgvJOQI1nlJBDWEyFC
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: owntracks-config-secret

