apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: basic-auth
spec:
  encryptedData:
    auth: AgAM1eqmQwSjsOhpcBKYxKeu3EvYTPJr7b5wCB5SImDViPLhfZ2Bh4ttjvYSdCCc4Le6wPsCHsyH0cBxwf0BQC3RoylBz/YKI/u6JYsJIyu/yrtz7iSbzMdGDD80uYfWEAp79f8dCd8KwkbGauiffdSBHSk4BfbOPwhx0y5ZS5QhwDqylIdPL/n2RP8ZRLzCh4AAiAMMj6e+mN8cipV1+xX+FF0RGSugmTkWEPjc63Y7eTaCmvH3JlMNw7D9LEOy0J/LdOo61NkNV+sGR4VFQPdiLzJadqctz8AFbkGL/gJVAOpXJ/3Zpd3VlFeA0/oLrfrLGt3OkJFuHk9z6/YEPMPvDwBVvdLb27wzz9b20Vef16Dt9CZT0YFs0s+9T7tOwNwipnxMO94d+coHfGDyM30EOvXuGfhU6T7jGCPYF5G9E9yVH4MeR1q7fYguUBTShkN3dxNNfPC+8RiBVmRCAV65s87AkrbF69bHl+o68oBgbKOfshlL+JScqLXORoFgaRwuNkMYevTALnQwx/SOSUtoigHbXUFltOyC0dljCeaqw5gdmsTMhOAfOOZoqCuXxQV2MyOSc2T/Q/kMzWoQ73DVFYG7Snyx6amrJqpWbSmDhDCBkwJGx3BvCDbI4cPDLfbaaoLSQ8Ebo7WkFazuWQhKJQ8ZUcZnPGdAmMsDqEubCHAS2WTEa+wAhEq75BXelsD6TbEfx2QFSYSNoEPP9rAZkm4HmZ20gBrAaGtXZmGpXMyHH7WmphlonMT7E8rXZfghtIkOumt/1XsHrpfm/9tzJrddAg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: basic-auth

