apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jlh
subjects:
- kind: User
  name: mail@jlh.name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

# Note: you can test the rbac with the following command:
# kubectl auth can-i -n tmeit --list --as system:serviceaccount:tmeit:gh-actions-deploy
