apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-apps
  namespace: argocd
  annotations:
    kubernetes.io/description: |
      This is the "app of apps" for the external_applications subdirectory.
      It loads all of the applications in that directory.
spec:
  project: default
  source:
    repoURL: https://github.com/JustinLex/jlh-h5b.git
    targetRevision: HEAD
    path: 'porygon_applications/external_applications'
  destination:
    name: in-cluster
    namespace: 'argocd'
  syncPolicy:
    automated:
