apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: smultronfeet-nu
  replicas: 1
  template:
    metadata:
      labels:
        app: smultronfeet-nu
    spec:
      containers:
      - name: website
        image: ghcr.io/justinlex/smultronfeet-nu:latest
        env:
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
        - name: tmp
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      dnsConfig:  # Fix DNS resolution in Alpine 3.11 https://github.com/kubernetes/kubernetes/issues/64924 https://github.com/gliderlabs/docker-alpine/issues/539
        options:
          - name: ndots
            value: "1"
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: smultronfeet-nu
spec:
  ports:
  - port: 8080
  selector:
    app: smultronfeet-nu
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website
spec:
  tls:
  - hosts:
      - smultronfeet.nu
    secretName: smultronfeet-nu-tls
  rules:
  - host: smultronfeet.nu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: website
            port:
              number: 8080
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smultronfeet-nu
spec:
  secretName: smultronfeet-nu-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - smultronfeet.nu
