apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  configuration.yaml: |
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://10.2.16.2
    serial:
      port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2485309-if00
      adapter: deconz
    
    homeassistant: true
    frontend: true

    permit_join: true
    
    devices: devices.yaml
    groups: groups.yaml
