apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  ports:
  - port: 80
    name: web
    targetPort: 8123
  clusterIP: None
  selector:
    app: home-assistant
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant # has to match .spec.template.metadata.labels
  serviceName: "home-assistant"
  replicas: 1
  template:
    metadata:
      labels:
        app: home-assistant # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:2024.1.6
        env:
        - name: TZ
          value: "Europe/Stockholm"
        ports:
        - containerPort: 8123
          name: web
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
      dnsConfig:  # Fix DNS resolution in Alpine 3.11 https://github.com/kubernetes/kubernetes/issues/64924 https://github.com/gliderlabs/docker-alpine/issues/539
        options:
          - name: ndots
            value: "1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  storageClassName: nfs-freenas
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
