apiVersion: v1
kind: Service
metadata:
  name: wireguard-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    component: wireguard
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
