apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jlh-name
spec:
  secretName: jlh-name-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - 'jlh.name'
  - '*.jlh.name'
