apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smultronfeet-nu
spec:
  secretName: smultronfeet-nu-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - smultronfeet.nu
