apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # Default is very low so most photo uploads will fail
    nginx.ingress.kubernetes.io/proxy-body-size: "4G"
  name: photoprism
spec:
  rules:
  - host: photos.jlh.name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: photoprism
            port:
              name: http
  tls:
  - hosts:
    - photos.jlh.name
    secretName: photoprism-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: photos-jlh-name
spec:
  secretName: photoprism-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - photos.jlh.name
