apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoprism-database
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: photoprism
  syncPolicy:
    automated: {}
  source:
    chart: mariadb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.*
    helm:
      releaseName: photoprism-mariadb
      parameters:
        - name: "auth.database"
          value: "photoprism"
        - name: "auth.username"
          value: "photoprism"
        - name: "auth.password"
          value: "photoprism"
