apiVersion: v1
kind: ServiceAccount
metadata:
  name: gh-actions-deploy
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-token-gh-actions-deploy
  annotations:
    kubernetes.io/service-account.name: "gh-actions-deploy"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gh-actions-deploy
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gh-actions-deploy
subjects:
- kind: ServiceAccount
  name: gh-actions-deploy
  namespace: tmeit
roleRef:
  kind: Role
  name: gh-actions-deploy
  apiGroup: rbac.authorization.k8s.io

# Note: you can test the rbac with the following command:
# kubectl auth can-i -n tmeit --list --as system:serviceaccount:tmeit:gh-actions-deploy
