apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: database-url
spec:
  encryptedData:
    DATABASE_URL: AgBBTENCqUla3xsRaUpdM6QaTGt0qq8r2iVaa4ttDhBAox1aFHpVnLyulYHCWyAsIXCtZg+VCefTGyoQ2spgXziITTXowaz73U6I4rRn6MPeWzd7QdOQW3OXtVc6pfj2b43ticiL8ii/2QV9GO4zwXgyDQmuYcmhjaxkLbu6HIMOCr/12/P+UkaRAmTXJ5wjhHhmPwDhlLjfVoG0J2YakA7egTlZ5FhtgbDjO6wGiPwJsGHDBDaqg0FzvXIx8i90biLdA01l7uCMtPnWhZibiMjMiGmaGXV+Y67OG/shUBeRAcwkXhVo5a0mI/j5gVRbf9wNFfWYRQt5I4+PJ/9zWRibW0dtHPyT2IY2AMwOTzxdV/VlYEZpnEGc8bLI6mmj92lVr4AOZBJRi6asTE8HqkJRPfsoNf2pcVfN5umYhNlRGx1gVlB4bgAMxj66hci3YWnyyfTzouCe17yQtW0q5MwTPH+TAwHJYeofwUw0to1XEzwW5d7ayWl9hWkY4buH0XVja1dy6qIES7Bc5a76bIXRibhfxU8wa37+3jw8mIqT39l9txBrdJKxrUPCX+0Xq3KHE0w/vAdF6S3G1bd5JTeAXUjfrHON+yewv6eZCHzYr9qnODFsIjvljT0BHvj3Gi6Wh1ferbG2P5kvaIL4BID+d1QebfIrpePyt2LTN+caAS3krVn0TpCfg4TmKvPqJSrGcZEankLtYRCcDYL9hsUW4VHAPcJUtFLWkvN66IavHUTgSP1BTuKH7jILkpGjjRUsJ88PEyvHnMdldg0GrD0TjWTSNciAgz8A0gUv7cyP
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: database-url

