apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: database-url
spec:
  encryptedData:
    DATABASE_URL: AgBmOhUWVytZJZvkPuzT7dFZsLhpz+4nJUobVb5TIBwu/4IDvx2DKbG1uxhDsPi85S1ANjNBZJ+iBz1fQTcB5IT6PjxcktneeuSd+LZnAm9Cj301K1fCNm42gxDldU3vV9mFeCFT6p5bvlgHior0BjM/Vv78USm6f/1b/sO0AaAruea+fsjGKPMxfdz415LXvfKA13vlA3lbF5OArBI4i0sFb2ff8YsBe8H4PUcmapQioZePRwRfL1kkD4WoR/8bcYGjGZ9orwur0xGzy/2ahCTBhSI2SeG/JX3u4oLJM+pQs+Cjn58INHfPHb+mQUm2jm57THx/VTbZ+eLblYGekxoE0JDW2B0j0jo5d3qApDvin/RccRycXT4lqkVMWhox0mvNchQfhDaZCaLJdiVeKwjNuuD5G8fD9VaRpN6vspqpBRUfGHxKAmMnWOjL09IrCn2UkhTsoYAHxr+ec28O3Zb71N3XE0DgRQa3N0VSvTCDSgfcKz0cG6gH4R1G+SvvdOBjrVYeVJRKKHtTKIvPOISggFDbCz33W78mvb70tCKzZJEG3bTalJ93bBj2IVz1kScfQfB6vd63/ZVQLn5HSSzmi+QFpM67PuNu2wYsKEE8bTjJ11TCztKrqYpdodIXtd93tcGZIieFUJxgpXB1rEDjrRtbRn5dX+mfjmZaF64lmOOpphUrbrT/VlKlOXN1I4IPwqUVFnoxYC8k/NyA9W+q5jaSHS2lYwjPJVG+wBgLeY9bhPufF5OVCDmltzqOh914PvUKcgSbh9XKWbQVWAU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: database-url

