apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: database-url
  namespace: my-namespace
spec:
  encryptedData:
    DATABASE_URL: AgBLD2ulIv9EBkayc//5ycLi7ELXBqwYYHH87F9Owlky56GjsaE1NGIPGUwtTX+prEjoFqQZn7ACNpO90y11a1icqqjBbNVI6epg1rdH+nCvmGevN+rK/k58QyodMj33zZJ2TqdvUPALuTBxa+r9+39ddpmqfu1IVWOIgPLaf7UhSu+o2gSsrWxaVwdTUO/H6caUw+g6QyE8olRdSF353aKxcFR4XHMn+hJR3f7ve9OUfclrZzFZjhljwEuYo3EGOOddHhG1D9TWEL9n8enHNZU1R1+lWPtjhpJEz4suQbKKSfDAocMTMH1CcvkVyj9IwOfhkwMqZJHwWRzgw9HM6pZ0nfm41qYgePgagKfJ394Fz97KmCf6SoosvtIFf38JjUPV5ruNIrl7eEXHgVEMw8GeSzO0tHfzAx7HlGJGXqDSUrnddVyvBWEkoHW90uMTxGDEdmwzWhUkwjO0G0I+tNk6m5/AiAjxB9LAGpuEdpPvPp+V2zdJqF7BDBxnIxCWTsYoM8zfQK308ZO/J56Xwi0xiP5KWvxLBXYwBFQet7Hys1hYjXyXTrSQsde1ohcmK8ExbW7z9kidmCpYCukLYBZ4FtWmc7/4JTzHhpQsiO6U/zaXETUdkwBy/iU5y4LiZ3MHrVGg8a1rNkgb2wZhc0MjaQKw4+Z5AJ4fK5JtNhlSbUoFR+kkM9Jh0W85q2cXfC5tobwP03CLgRTe974ahsxe8ri5o0cDnGTcCbn3YUOe16Fho/HY+8m8/oAqIRCED6cXSfpSlqQcvpQ2Q8pnsrc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: database-url
      namespace: my-namespace

