apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: database-url
spec:
  encryptedData:
    DATABASE_URL: AgA1o568NnKvHZq4kIhZ/9nOOlOh1kA2fUehyY8r3TA4m7uvJ4T1OK2HbZ4awjFijTrbAmhGxjzwVezGMA2C5h1wV+GEaVHLlhKUsJTPUD/MFM9bOxPz5ol5vyC4smXDhcfZ/H+yU4swzZnTF1g/HOEjBzs10YAqBvC3fuavQM79aBvZ1P3kPtXllqMgYphQsSWTTM1iyldWPMrHcFHqXUBUlbUkcDvzKArk16LJZm0apnjQ4IGZJzGv4ugvvL35pD6+IKQhkePvkjZ2fZGyFOQYW9oc5OXmiS7TXdE1an1AifAvOFEUhojz6pcWP+zxyXqyYkcH/ur7k62Psn3gxWGFUmgimMd1Fg6wysXvQrhqyTntZUlzLTCBkwolSuFsMKotVC8GVUL6f2xlNhxUJtZ1F/CHlU6XNAR2tZpJovZ/mkGWTC/4Ox17NZxsUu8TwCTNOHX6rHisEmFY8g/r4yADS6GhwkdPKip2wNJLMp81qVAjfkDJL2BE0FOmWbVSUhAYGWsh4Pxj7TBwbfnTd6D0SvFRN/6D6/IwyIwIvab4PwamVIT1zM01Ltwj5Ey2mqvwESZcbABsqVla0XSp7/oV/3skBrWbY9/sbgaoTQQtNLXB2XCmbPSZ07fg5gPqLKodxwzj0g1n065rDhfuRIpR2TkEIVIH15fFSQBqnzTFSJ2iQrwEqlxJwYuWodsWXYlTT/Njbtwg+9cFUgrAI73/eE8T2h0iQn7+UVV/qhr3qJlGQObUwpZvs0W50XyTsACJwb5Fr7MxvEPQ4Y4Fx6tx6QE=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: database-url

