apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: database-url
spec:
  encryptedData:
    DATABASE_URL: AgAYjqsJuJv2bAYfHv/WP3yW3axI4lHF5bjfyvAT0H+VCay51kBn8HInHnQt4hbQUrnbqk1VpIsLPG5BH48v4dw+iiZtieyzI8AFP4AjulPqX2zjkgklrBCi7xfpGOVdaC2Dz++rTpve0i5mrTxdd/wMQ0V8wisDFULMFg9bIa1FeqkJGQQihA0BpIj9AYyc6bljwoazDzCgD9llSZw8MWWvyxVFrwg1bspf7kQnvSVwDNVZfEXW0WzbEWFGBI+UQ8HFhfLH6NJ2PxLV7YxNzePyMGf6A0L1xowQ9GfE8w+7VGSPWVbe9SkOFBFszIiM7a4X/FTqlLiE+F2/5gNPTPEIgcWvejAaOlRMwdJFI2xWsUnCTHs1EdgqwO5oT26z26iY75DRUMhd8ua0rk8K7C8wM7MRoq8Yx4v8DJh1+ZEczek2O5rHjiM5K5T+0JOOVS9jxNHbYScHDEhga7EYCmgOCqv+3qlw70tRjsaFa1ZNrLxg4/oDJK3V/OUPke9qZ4Lin0anHFji8mgxZsgqoBJdE4AdtAm3CrKUVQfpwFs/NWZ5CbfUam3Vpm9VXtS+jIuQZMRyvEmvelAKmhxlV6mmi4v6tr1wgoLSWdxfBRg4Pb9xXfBpeQrtY7+THkX1oQum9Io0pHXfJgVT0awzNazgLvS++Z+b2nOzlqJbvpp3Llw6dQ2JwESx1IEG5eMoW2HgKFesHOx+yB0zEHfDZaMA16TyTK9LAEZNv6Sz6ciueskn2BnMH8b10rlpiUm6ANXG8Jf1PcZAgHDZJWEzoiRNLjg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: database-url

