apiVersion: v1
kind: Pod
metadata:
  name: ssh-test
spec:
  containers:
  - name: backup-solid
    image: kroniak/ssh-client:latest
    args:
    - sleep
    - "10000"
#    - ssh
#    - "-o"
#    - StrictHostKeyChecking=no
#    - root@ditto.home.jlh.name
#    - /bin/bash
#    - /root/backup.sh

    volumeMounts:
      - name: ssh-key
        mountPath: "/root/.ssh"
  volumes:
    - name: ssh-key
      secret:
        secretName: ditto-ssh-key
        defaultMode: 0400
  dnsConfig: # Fix DNS resolution in Alpine 3.11 https://github.com/kubernetes/kubernetes/issues/64924 https://github.com/gliderlabs/docker-alpine/issues/539
    options:
      - name: ndots
        value: "1"